apiVersion: v1
kind: Service
metadata:
  name: { { include "cert-manager-webhook-cloudns-v2.fullname" . } }
  labels:
    app: { { include "cert-manager-webhook-cloudns-v2.name" . } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: { { include "cert-manager-webhook-cloudns-v2.name" . } }
